### ISSUE TITLE
Hi,please help me  convert nltx file

### ISSUE THREAD

**Issue by imjinjia** [iltrof/ykcmp#1]
thanks!
https://zenhax.com/viewtopic.php?f=9&t=13285

**Comment by iltrof** [comment]
The YKCMP archive inside the files can be extracted just fine with:
```powershell
.\ykcmp.exe -a 0x80 1.nltx
```

The result, however, is a texture in an unknown format, shuffled in an unknown way. I'd have to figure out which format that is and the exact algorithm which was used to shuffle the texture. And I _really_ don't have the time or motivation to go through all of that, sorry.

I'll leave some pointers on the forum if someone else wants to deal with this. Also, you should at least tell people which game and platform the .nltx files came from.

Since this isn't really a ykcmp-related issue, I'll be closing this.
